[package]
name = "moor-values"
version = "0.1.0"
authors.workspace = true
categories.workspace = true
edition.workspace = true
keywords.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "The set of values, and model/entities used across the system"

[dependencies]
binary-layout.workspace = true
bincode.workspace = true
bytes.workspace = true
daumtils.workspace = true
decorum.workspace = true
enum-primitive-derive.workspace = true
itertools.workspace = true
lazy_static.workspace = true
num-traits.workspace = true
paste.workspace = true
strum.workspace = true
thiserror.workspace = true
ustr.workspace = true
uuid.workspace = true

[features]
# If List and String are backed by Bytes instead of Arc<Vec<Var>> and Arc<String> respectively.
list_impl_buffer = []
default = []
