[package]
name = "moor-values"
version = "0.1.0"
description = "The set of values, and model/entities used across the system"
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
categories.workspace = true
keywords.workspace = true
readme.workspace = true

[dependencies]
binary-layout.workspace = true
bincode.workspace = true
bytes.workspace = true
daumtils.workspace = true
decorum.workspace = true
enum-primitive-derive.workspace = true
itertools.workspace = true
lazy_static.workspace = true
num-traits.workspace = true
strum.workspace = true
thiserror.workspace = true
uuid.workspace = true
yoke.workspace = true
paste.workspace = true
