licenses:
  - files: any
    ident: GPL-3.0
    authors:
      - name: Ryan Daum
        email: ryan.daum@gmail.com
    auto_template: true

comments:
  - columns: 80
    extension: rs
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
  - columns: 80
    extension: h
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
  - columns: 80
    extension: pest
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
  - columns: 80
    extension: js
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
  - columns: 80
    extension: ts
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
  - columns: 80
    extension: tsx
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
  - columns: 80
    extension: jsx
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
  - columns: 80
    extension: fbs
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
  - columns: 80
    extension: moo
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
  - columns: 80
    extension: py
    commenter:
      type: line
      comment_char: "#"
      trailing_lines: 1
  - columns: 80
    extension: sh
    commenter:
      type: line
      comment_char: "#"
      trailing_lines: 1

excludes:
  - \.gitignore
  - \.dockerignore
  - \.gitmodules
  - \.vscodeignore
  - .*lock
  - \.git/.*
  - \.idea/.*
  - \.cargo/.*
  - target/*
  - README.*
  - LICENSE.*
  - Dockerfile
  - core
  - cores/*
  - cores/cowbell/*
  - book/*
  - lambdamoo/*
  - __pycache__/*
  - .envrc
  - .*\.env$
  - .*\.env\..*
  - node_modules/*
  - development-export/*
  - crates/daemon/debian/*
  - crates/telnet-host/debian/*
  - crates/web-host/debian/*
  - tools/example-python-worker/moor_schema/*
  - generated/*
  - web-client/public/*
  - .*\.(md|rst|txt|yml|yaml|png|jpg|gif|db|pem|lock|json|toml|in|out|html|moot|edn|node|css|gz|tgz|tar|zip|awk|data|conf|nix|el|ttf|otf|wasm|cfg)
