licenses:
  - files: any
    ident: GPL-3.0
    authors:
      - name: Ryan Daum
        email: ryan.daum@gmail.com
    auto_template: true

comments:
  - columns: 80
    extension: rs
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
  - columns: 80
    extension: h
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
  - columns: 80
    extension: pest
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1
  - columns: 80
    extension: js
    commenter:
      type: line
      comment_char: "//"
      trailing_lines: 1

excludes:
  - \.gitignore
  - \.gitmodules
  - \.vscodeignore
  - .*lock
  - \.git/.*
  - \.idea/.*
  - \.cargo/.*
  - crates/web-host/src/client/flexbuffers/*
  - crates/db-wiredtiger/third-party/*
  - target/.*
  - README.*
  - LICENSE.*
  - Dockerfile
  - core
  - .*\.(md|rst|txt|yml|png|jpg|gif|db|pem|lock|json|toml|in|out|html|moot)
