# Pre-commit config that matches GitHub CI checks
# This version works even when code doesn't fully compile
repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-toml
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: detect-private-key
        exclude: |
          (?x)^(
            crates/daemon/src/main\.rs|
            crates/daemon/src/testing/.*|
            crates/telnet-host/tests/.*
          )$

  # Rust formatting check (this is what GitHub CI runs)
  - repo: local
    hooks:
      - id: cargo-fmt-check
        name: cargo fmt --check
        entry: bash -c 'cargo fmt --all -- --check || echo "Run cargo fmt --all to fix formatting"'
        language: system
        types: [rust]
        pass_filenames: false

  # TOML formatting
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix]

  # License header check (commented out for now)
  # - repo: local
  #   hooks:
  #     - id: license-header-check
  #       name: Check license headers
  #       entry: bash
  #       args: ['-c', 'for f in $(find crates -name "*.rs" -type f); do if ! head -n 1 "$f" | grep -q "^// Copyright (C) [0-9]* Ryan Daum"; then echo "$f: Missing or incorrect license header"; exit 1; fi; done']
  #       language: system
  #       types: [rust]
  #       pass_filenames: false

# Configuration
default_stages: [pre-commit]
fail_fast: false
exclude: |
  (?x)^(
    target/|
    Cargo\.lock|
    .*\.snap$|
    .*\.bak$|
    JHCore.*\.db$
  )
