name: Builtin Stability Check

on: [pull_request]

jobs:
  check_builtins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check builtin table stability
        run: ./scripts/check-builtin-stability.sh
