name: Frontend CI

on: [push, pull_request]

jobs:
  frontend-ci:
    runs-on: ubuntu-latest
    container: node:20
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run lint
      run: npm run lint
    
    - name: Run TypeScript compilation
      run: npm run build