# Uses licensure to make sure the GPL3 blurb is at the top of every relevant file.

name: License check

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_license:
    runs-on: ubuntu-latest
    container: moor-ci:1.90.0
    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: licensure --check -p -v
