name: Release - Build and push Docker images

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (tag or commit hash) to build from'
        required: true
        type: string

env:
  REGISTRY: codeberg.org
  IMAGE_NAME: timbran/moor

jobs:
  build_docker:
    strategy:
      matrix:
        include:
          - arch: x86_64
            runs-on: linux-x86
            dockerfile: Dockerfile
          - arch: aarch64
            runs-on: linux-arm64
            dockerfile: Dockerfile.arm64-cross
    runs-on: ${{ matrix.runs-on }}
    container: moor-ci:1.90.0
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          submodules: 'true'

      - name: Log in to Codeberg Container Registry
        run: |
          echo "${{ secrets.CODEBERG_TOKEN }}" | docker login ${{ env.REGISTRY }} -u timbran --password-stdin

      - name: Build Docker image (${{ matrix.arch }})
        run: |
          docker build \
            --file ${{ matrix.dockerfile }} \
            --target default \
            --build-arg BUILD_PROFILE=release \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.ref }}-${{ matrix.arch }} \
            .

      - name: Push Docker image (${{ matrix.arch }})
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.ref }}-${{ matrix.arch }}

      - name: Log out from Codeberg Container Registry
        run: docker logout ${{ env.REGISTRY }}
