name: Release - Build and publish Debian packages and Docker images

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git ref (tag or commit hash) to build from'
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always
  REGISTRY: codeberg.org
  IMAGE_NAME: timbran/moor

jobs:
  build_and_publish:
    strategy:
      matrix:
        include:
          - arch: x86_64
            runs-on: linux-x86
            dockerfile: Dockerfile
          - arch: aarch64
            runs-on: linux-arm64
            dockerfile: Dockerfile.arm64-cross
    runs-on: ${{ matrix.runs-on }}
    container: moor-ci:1.90.0
    outputs:
      x86_64-packages: ${{ steps.list-packages.outputs.x86_64 }}
      aarch64-packages: ${{ steps.list-packages.outputs.aarch64 }}
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          submodules: 'true'

      # Build Debian packages
      - name: Build binaries with release profile
        run: CARGO_BUILD_JOBS=4 cargo build --release -p moor-daemon -p moor-telnet-host -p moor-web-host -p moor-curl-worker -p moorc -p moor-emh -p moor-mcp-host -j 4

      - name: Check prerequisites for Debian packages
        run: |
          echo "Checking for cargo-deb..."
          command -v cargo-deb || cargo install cargo-deb
          echo "Checking for npm..."
          command -v npm || echo "WARNING: npm not found, skipping web client"

      - name: Import GPG key for package signing
        if: ${{ secrets.GPG_PRIVATE_KEY != '' }}
        run: |
          echo "Importing GPG key for package signing..."
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import
          echo "GPG key imported successfully"
          gpg --list-secret-keys

      - name: Build Debian packages
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: |
          # Determine if we should sign packages
          SIGN_FLAG=""
          if [ -n "$GPG_KEY_ID" ]; then
            echo "GPG key ID found, packages will be signed with key: $GPG_KEY_ID"
            SIGN_FLAG="--deb-sign=$GPG_KEY_ID"
          else
            echo "No GPG key ID found, packages will not be signed"
          fi

          for pkg in moor-daemon moor-telnet-host moor-web-host moor-curl-worker moorc moor-emh moor-mcp-host; do
            echo "Building $pkg package..."
            cargo deb -p "$pkg" --profile release --no-build $SIGN_FLAG
          done

      - name: Build web client (if npm available)
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        run: |
          if command -v npm &> /dev/null; then
            echo "Building web client..."
            npm ci
            npm run build
            echo "Building moor-web-client package..."
            ./deploy/debian-packages/build-web-client-deb.sh
          else
            echo "npm not found, skipping web client"
          fi

      - name: List built Debian packages
        id: list-packages
        run: |
          echo "Built .deb packages:"
          ls -lh target/debian/*.deb
          PACKAGES=$(ls -1 target/debian/*.deb | tr '\n' ' ')
          echo "${{ matrix.arch }}=$PACKAGES" >> $GITHUB_OUTPUT

      - name: Upload Debian packages as workflow artifacts
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: debian-packages-${{ matrix.arch }}
          path: target/debian/*.deb

      - name: Publish Debian packages to Codeberg repository
        run: |
          for deb_file in target/debian/*.deb; do
            if [ -f "$deb_file" ]; then
              echo "Uploading $deb_file to Codeberg Debian repository..."
              curl --user timbran:${{ secrets.CODEBERG_TOKEN }} \
                   --upload-file "$deb_file" \
                   https://codeberg.org/api/packages/timbran/debian/pool/bookworm/main/upload
              echo "Uploaded: $deb_file"
            fi
          done

      # Build Docker images
      - name: Log in to Codeberg Container Registry
        run: |
          echo "${{ secrets.CODEBERG_TOKEN }}" | docker login ${{ env.REGISTRY }} -u timbran --password-stdin

      - name: Build backend Docker image (${{ matrix.arch }})
        run: |
          docker build \
            --file ${{ matrix.dockerfile }} \
            --target default \
            --build-arg BUILD_PROFILE=release \
            --build-arg CARGO_BUILD_JOBS=2 \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.ref }}-${{ matrix.arch }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-${{ matrix.arch }} \
            .

      - name: Build frontend Docker image (${{ matrix.arch }})
        run: |
          docker build \
            --file ${{ matrix.dockerfile }} \
            --target frontend \
            --build-arg BUILD_PROFILE=release \
            --build-arg CARGO_BUILD_JOBS=2 \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:${{ inputs.ref }}-${{ matrix.arch }} \
            -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest-${{ matrix.arch }} \
            .

      - name: Push Docker images (${{ matrix.arch }})
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.ref }}-${{ matrix.arch }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest-${{ matrix.arch }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:${{ inputs.ref }}-${{ matrix.arch }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-frontend:latest-${{ matrix.arch }}

      - name: Log out from Codeberg Container Registry
        run: docker logout ${{ env.REGISTRY }}

  create_release:
    needs: build_and_publish
    runs-on: linux-x86
    container: moor-ci:1.90.0
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Install jq
        run: apt-get update && apt-get install -y jq

      - name: Download all Debian packages
        uses: https://code.forgejo.org/forgejo/download-artifact@v4
        with:
          path: debian-artifacts

      - name: Create release
        env:
          FORGEJO_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          # Check if release already exists
          RELEASE_EXISTS=$(curl -s -H "Authorization: token $FORGEJO_TOKEN" \
            https://codeberg.org/api/v1/repos/timbran/moor/releases/tags/${{ inputs.ref }} | jq -r '.id // empty')

          if [ -z "$RELEASE_EXISTS" ]; then
            echo "Creating new release for ${{ inputs.ref }}..."
            curl -X POST \
              -H "Authorization: token $FORGEJO_TOKEN" \
              -H "Content-Type: application/json" \
              -d '{
                "tag_name": "${{ inputs.ref }}",
                "target_commitish": "${{ inputs.ref }}",
                "name": "Release ${{ inputs.ref }}",
                "body": "## mooR Release ${{ inputs.ref }}\n\n### Downloads\n\n**Debian Packages:**\n- Available in the release artifacts below\n\n**Docker Images:**\n- Backend: `codeberg.org/timbran/moor:${{ inputs.ref }}-x86_64` and `:${{ inputs.ref }}-aarch64`\n- Frontend: `codeberg.org/timbran/moor-frontend:${{ inputs.ref }}-x86_64` and `:${{ inputs.ref }}-aarch64`\n- Latest tags: `:latest-x86_64` and `:latest-aarch64`",
                "draft": false,
                "prerelease": false
              }' \
              https://codeberg.org/api/v1/repos/timbran/moor/releases
          else
            echo "Release ${{ inputs.ref }} already exists"
          fi

      - name: Upload Debian packages to release
        env:
          FORGEJO_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        run: |
          # Get the release ID from the tag
          RELEASE_ID=$(curl -s -H "Authorization: token $FORGEJO_TOKEN" \
            https://codeberg.org/api/v1/repos/timbran/moor/releases/tags/${{ inputs.ref }} | jq -r '.id')

          if [ -z "$RELEASE_ID" ] || [ "$RELEASE_ID" = "null" ]; then
            echo "ERROR: Could not find release ID for tag ${{ inputs.ref }}"
            exit 1
          fi

          echo "Found release ID: $RELEASE_ID"

          # Find all .deb files recursively
          find debian-artifacts -name "*.deb" -type f | while read deb_file; do
            filename=$(basename "$deb_file")
            echo "Uploading $filename to release..."
            curl -X POST \
              -H "Authorization: token $FORGEJO_TOKEN" \
              -F "attachment=@$deb_file" \
              "https://codeberg.org/api/v1/repos/timbran/moor/releases/${RELEASE_ID}/assets?name=${filename}"
          done
