# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorVar

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VarAnonymous(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VarAnonymous()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVarAnonymous(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VarAnonymous
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VarAnonymous
    def Obj(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def VarAnonymousStart(builder): builder.StartObject(1)
def Start(builder):
    return VarAnonymousStart(builder)
def VarAnonymousAddObj(builder, obj): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(obj), 0)
def AddObj(builder, obj):
    return VarAnonymousAddObj(builder, obj)
def VarAnonymousEnd(builder): return builder.EndObject()
def End(builder):
    return VarAnonymousEnd(builder)