# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorVar

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VarErr(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VarErr()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVarErr(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VarErr
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VarErr
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Error import Error
            obj = Error()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def VarErrStart(builder): builder.StartObject(1)
def Start(builder):
    return VarErrStart(builder)
def VarErrAddError(builder, error): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)
def AddError(builder, error):
    return VarErrAddError(builder, error)
def VarErrEnd(builder): return builder.EndObject()
def End(builder):
    return VarErrEnd(builder)