# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorVar

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VarList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VarList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVarList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VarList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VarList
    def Elements(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorVar.Var import Var
            obj = Var()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VarList
    def ElementsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VarList
    def ElementsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def VarListStart(builder):
    builder.StartObject(1)

def Start(builder):
    VarListStart(builder)

def VarListAddElements(builder, elements):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(elements), 0)

def AddElements(builder, elements):
    VarListAddElements(builder, elements)

def VarListStartElementsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartElementsVector(builder, numElems: int) -> int:
    return VarListStartElementsVector(builder, numElems)

def VarListEnd(builder):
    return builder.EndObject()

def End(builder):
    return VarListEnd(builder)
