# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorProgram

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LineSpan(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LineSpan()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLineSpan(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LineSpan
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LineSpan
    def Offset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # LineSpan
    def LineNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def LineSpanStart(builder): builder.StartObject(2)
def Start(builder):
    return LineSpanStart(builder)
def LineSpanAddOffset(builder, offset): builder.PrependUint64Slot(0, offset, 0)
def AddOffset(builder, offset):
    return LineSpanAddOffset(builder, offset)
def LineSpanAddLineNumber(builder, lineNumber): builder.PrependUint64Slot(1, lineNumber, 0)
def AddLineNumber(builder, lineNumber):
    return LineSpanAddLineNumber(builder, lineNumber)
def LineSpanEnd(builder): return builder.EndObject()
def End(builder):
    return LineSpanEnd(builder)