# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorProgram

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StoredNames(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StoredNames()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStoredNames(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StoredNames
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StoredNames
    def GlobalWidth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # StoredNames
    def Decls(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorProgram.StoredNameDeclPair import StoredNameDeclPair
            obj = StoredNameDeclPair()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StoredNames
    def DeclsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # StoredNames
    def DeclsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def StoredNamesStart(builder): builder.StartObject(2)
def Start(builder):
    return StoredNamesStart(builder)
def StoredNamesAddGlobalWidth(builder, globalWidth): builder.PrependUint64Slot(0, globalWidth, 0)
def AddGlobalWidth(builder, globalWidth):
    return StoredNamesAddGlobalWidth(builder, globalWidth)
def StoredNamesAddDecls(builder, decls): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(decls), 0)
def AddDecls(builder, decls):
    return StoredNamesAddDecls(builder, decls)
def StoredNamesStartDeclsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartDeclsVector(builder, numElems):
    return StoredNamesStartDeclsVector(builder, numElems)
def StoredNamesEnd(builder): return builder.EndObject()
def End(builder):
    return StoredNamesEnd(builder)