# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorProgram

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StoredRangeComprehend(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StoredRangeComprehend()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStoredRangeComprehend(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StoredRangeComprehend
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StoredRangeComprehend
    def Position(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorProgram.StoredName import StoredName
            obj = StoredName()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StoredRangeComprehend
    def EndOfRangeRegister(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorProgram.StoredName import StoredName
            obj = StoredName()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StoredRangeComprehend
    def EndLabel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def StoredRangeComprehendStart(builder): builder.StartObject(3)
def Start(builder):
    return StoredRangeComprehendStart(builder)
def StoredRangeComprehendAddPosition(builder, position): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(position), 0)
def AddPosition(builder, position):
    return StoredRangeComprehendAddPosition(builder, position)
def StoredRangeComprehendAddEndOfRangeRegister(builder, endOfRangeRegister): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(endOfRangeRegister), 0)
def AddEndOfRangeRegister(builder, endOfRangeRegister):
    return StoredRangeComprehendAddEndOfRangeRegister(builder, endOfRangeRegister)
def StoredRangeComprehendAddEndLabel(builder, endLabel): builder.PrependUint16Slot(2, endLabel, 0)
def AddEndLabel(builder, endLabel):
    return StoredRangeComprehendAddEndLabel(builder, endLabel)
def StoredRangeComprehendEnd(builder): return builder.EndObject()
def End(builder):
    return StoredRangeComprehendEnd(builder)