# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorProgram

class StoredScatterLabelUnion(object):
    NONE = 0
    StoredScatterRequired = 1
    StoredScatterOptional = 2
    StoredScatterRest = 3
