# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorProgram

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StoredJumpLabel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StoredJumpLabel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStoredJumpLabel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StoredJumpLabel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StoredJumpLabel
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # StoredJumpLabel
    def Position(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # StoredJumpLabel
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorProgram.StoredName import StoredName
            obj = StoredName()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def StoredJumpLabelStart(builder):
    builder.StartObject(3)

def Start(builder):
    StoredJumpLabelStart(builder)

def StoredJumpLabelAddId(builder, id):
    builder.PrependUint16Slot(0, id, 0)

def AddId(builder, id):
    StoredJumpLabelAddId(builder, id)

def StoredJumpLabelAddPosition(builder, position):
    builder.PrependUint16Slot(1, position, 0)

def AddPosition(builder, position):
    StoredJumpLabelAddPosition(builder, position)

def StoredJumpLabelAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    StoredJumpLabelAddName(builder, name)

def StoredJumpLabelEnd(builder):
    return builder.EndObject()

def End(builder):
    return StoredJumpLabelEnd(builder)
