# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorProgram

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StoredForSequenceOperand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StoredForSequenceOperand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStoredForSequenceOperand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StoredForSequenceOperand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StoredForSequenceOperand
    def ValueBind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorProgram.StoredName import StoredName
            obj = StoredName()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StoredForSequenceOperand
    def KeyBind(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorProgram.StoredName import StoredName
            obj = StoredName()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StoredForSequenceOperand
    def EndLabel(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # StoredForSequenceOperand
    def EnvironmentWidth(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def StoredForSequenceOperandStart(builder):
    builder.StartObject(4)

def Start(builder):
    StoredForSequenceOperandStart(builder)

def StoredForSequenceOperandAddValueBind(builder, valueBind):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(valueBind), 0)

def AddValueBind(builder, valueBind):
    StoredForSequenceOperandAddValueBind(builder, valueBind)

def StoredForSequenceOperandAddKeyBind(builder, keyBind):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(keyBind), 0)

def AddKeyBind(builder, keyBind):
    StoredForSequenceOperandAddKeyBind(builder, keyBind)

def StoredForSequenceOperandAddEndLabel(builder, endLabel):
    builder.PrependUint16Slot(2, endLabel, 0)

def AddEndLabel(builder, endLabel):
    StoredForSequenceOperandAddEndLabel(builder, endLabel)

def StoredForSequenceOperandAddEnvironmentWidth(builder, environmentWidth):
    builder.PrependUint16Slot(3, environmentWidth, 0)

def AddEnvironmentWidth(builder, environmentWidth):
    StoredForSequenceOperandAddEnvironmentWidth(builder, environmentWidth)

def StoredForSequenceOperandEnd(builder):
    return builder.EndObject()

def End(builder):
    return StoredForSequenceOperandEnd(builder)
