# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorProgram

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StoredNamedVar(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StoredNamedVar()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStoredNamedVar(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StoredNamedVar
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StoredNamedVar
    def Symbol(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Symbol import Symbol
            obj = Symbol()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def StoredNamedVarStart(builder): builder.StartObject(1)
def Start(builder):
    return StoredNamedVarStart(builder)
def StoredNamedVarAddSymbol(builder, symbol): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(symbol), 0)
def AddSymbol(builder, symbol):
    return StoredNamedVarAddSymbol(builder, symbol)
def StoredNamedVarEnd(builder): return builder.EndObject()
def End(builder):
    return StoredNamedVarEnd(builder)