# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AmbiguousMatch(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AmbiguousMatch()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAmbiguousMatch(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AmbiguousMatch
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AmbiguousMatch
    def MatchString(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def AmbiguousMatchStart(builder):
    builder.StartObject(1)

def Start(builder):
    AmbiguousMatchStart(builder)

def AmbiguousMatchAddMatchString(builder, matchString):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(matchString), 0)

def AddMatchString(builder, matchString):
    AmbiguousMatchAddMatchString(builder, matchString)

def AmbiguousMatchEnd(builder):
    return builder.EndObject()

def End(builder):
    return AmbiguousMatchEnd(builder)
