# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ChparentPropertyNameConflict(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ChparentPropertyNameConflict()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsChparentPropertyNameConflict(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ChparentPropertyNameConflict
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ChparentPropertyNameConflict
    def Descendant(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChparentPropertyNameConflict
    def Ancestor(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ChparentPropertyNameConflict
    def Property(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ChparentPropertyNameConflictStart(builder): builder.StartObject(3)
def Start(builder):
    return ChparentPropertyNameConflictStart(builder)
def ChparentPropertyNameConflictAddDescendant(builder, descendant): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(descendant), 0)
def AddDescendant(builder, descendant):
    return ChparentPropertyNameConflictAddDescendant(builder, descendant)
def ChparentPropertyNameConflictAddAncestor(builder, ancestor): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ancestor), 0)
def AddAncestor(builder, ancestor):
    return ChparentPropertyNameConflictAddAncestor(builder, ancestor)
def ChparentPropertyNameConflictAddProperty(builder, property): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(property), 0)
def AddProperty(builder, property):
    return ChparentPropertyNameConflictAddProperty(builder, property)
def ChparentPropertyNameConflictEnd(builder): return builder.EndObject()
def End(builder):
    return ChparentPropertyNameConflictEnd(builder)