# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

class CompileErrorUnion(object):
    NONE = 0
    StringLexError = 1
    ParseError = 2
    UnknownBuiltinFunction = 3
    UnknownTypeConstant = 4
    UnknownLoopLabel = 5
    DuplicateVariable = 6
    AssignToConst = 7
    DisabledFeature = 8
    BadSlotName = 9
    InvalidAssignment = 10
    InvalidTypeLiteralAssignment = 11
