# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DuplicatePropertyDefinition(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DuplicatePropertyDefinition()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDuplicatePropertyDefinition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DuplicatePropertyDefinition
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DuplicatePropertyDefinition
    def Obj(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DuplicatePropertyDefinition
    def Property(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DuplicatePropertyDefinitionStart(builder): builder.StartObject(2)
def Start(builder):
    return DuplicatePropertyDefinitionStart(builder)
def DuplicatePropertyDefinitionAddObj(builder, obj): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(obj), 0)
def AddObj(builder, obj):
    return DuplicatePropertyDefinitionAddObj(builder, obj)
def DuplicatePropertyDefinitionAddProperty(builder, property): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(property), 0)
def AddProperty(builder, property):
    return DuplicatePropertyDefinitionAddProperty(builder, property)
def DuplicatePropertyDefinitionEnd(builder): return builder.EndObject()
def End(builder):
    return DuplicatePropertyDefinitionEnd(builder)