# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InvalidAssignment(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InvalidAssignment()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInvalidAssignment(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InvalidAssignment
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InvalidAssignment
    def Context(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.CompileContext import CompileContext
            obj = CompileContext()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def InvalidAssignmentStart(builder):
    builder.StartObject(1)

def Start(builder):
    InvalidAssignmentStart(builder)

def InvalidAssignmentAddContext(builder, context):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(context), 0)

def AddContext(builder, context):
    InvalidAssignmentAddContext(builder, context)

def InvalidAssignmentEnd(builder):
    return builder.EndObject()

def End(builder):
    return InvalidAssignmentEnd(builder)
