# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class NotifyEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NotifyEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNotifyEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # NotifyEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NotifyEvent
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorVar.Var import Var
            obj = Var()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NotifyEvent
    def ContentType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Symbol import Symbol
            obj = Symbol()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NotifyEvent
    def NoFlush(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # NotifyEvent
    def NoNewline(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # NotifyEvent
    def Metadata(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorCommon.EventMetadata import EventMetadata
            obj = EventMetadata()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # NotifyEvent
    def MetadataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # NotifyEvent
    def MetadataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def NotifyEventStart(builder): builder.StartObject(5)
def Start(builder):
    return NotifyEventStart(builder)
def NotifyEventAddValue(builder, value): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)
def AddValue(builder, value):
    return NotifyEventAddValue(builder, value)
def NotifyEventAddContentType(builder, contentType): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(contentType), 0)
def AddContentType(builder, contentType):
    return NotifyEventAddContentType(builder, contentType)
def NotifyEventAddNoFlush(builder, noFlush): builder.PrependBoolSlot(2, noFlush, 0)
def AddNoFlush(builder, noFlush):
    return NotifyEventAddNoFlush(builder, noFlush)
def NotifyEventAddNoNewline(builder, noNewline): builder.PrependBoolSlot(3, noNewline, 0)
def AddNoNewline(builder, noNewline):
    return NotifyEventAddNoNewline(builder, noNewline)
def NotifyEventAddMetadata(builder, metadata): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(metadata), 0)
def AddMetadata(builder, metadata):
    return NotifyEventAddMetadata(builder, metadata)
def NotifyEventStartMetadataVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartMetadataVector(builder, numElems):
    return NotifyEventStartMetadataVector(builder, numElems)
def NotifyEventEnd(builder): return builder.EndObject()
def End(builder):
    return NotifyEventEnd(builder)