# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Obj(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Obj()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsObj(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Obj
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Obj
    def ObjType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Obj
    def Obj(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def ObjStart(builder):
    builder.StartObject(2)

def Start(builder):
    ObjStart(builder)

def ObjAddObjType(builder, objType):
    builder.PrependUint8Slot(0, objType, 0)

def AddObjType(builder, objType):
    ObjAddObjType(builder, objType)

def ObjAddObj(builder, obj):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(obj), 0)

def AddObj(builder, obj):
    ObjAddObj(builder, obj)

def ObjEnd(builder):
    return builder.EndObject()

def End(builder):
    return ObjEnd(builder)
