# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ObjectRef(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ObjectRef()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsObjectRef(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ObjectRef
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ObjectRef
    def RefType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ObjectRef
    def Ref(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def ObjectRefStart(builder):
    builder.StartObject(2)

def Start(builder):
    ObjectRefStart(builder)

def ObjectRefAddRefType(builder, refType):
    builder.PrependUint8Slot(0, refType, 0)

def AddRefType(builder, refType):
    ObjectRefAddRefType(builder, refType)

def ObjectRefAddRef(builder, ref):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(ref), 0)

def AddRef(builder, ref):
    ObjectRefAddRef(builder, ref)

def ObjectRefEnd(builder):
    return builder.EndObject()

def End(builder):
    return ObjectRefEnd(builder)
