# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

class ObjectRefUnion(object):
    NONE = 0
    ObjectRefId = 1
    ObjectRefSysObj = 2
    ObjectRefMatch = 3
