# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ObjId(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ObjId()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsObjId(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ObjId
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ObjId
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def ObjIdStart(builder): builder.StartObject(1)
def Start(builder):
    return ObjIdStart(builder)
def ObjIdAddId(builder, id): builder.PrependInt32Slot(0, id, 0)
def AddId(builder, id):
    return ObjIdAddId(builder, id)
def ObjIdEnd(builder): return builder.EndObject()
def End(builder):
    return ObjIdEnd(builder)