# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PresentEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PresentEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPresentEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PresentEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PresentEvent
    def Presentation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Presentation import Presentation
            obj = Presentation()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def PresentEventStart(builder):
    builder.StartObject(1)

def Start(builder):
    PresentEventStart(builder)

def PresentEventAddPresentation(builder, presentation):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(presentation), 0)

def AddPresentation(builder, presentation):
    PresentEventAddPresentation(builder, presentation)

def PresentEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return PresentEventEnd(builder)
