# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PropertyTypeMismatch(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PropertyTypeMismatch()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPropertyTypeMismatch(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PropertyTypeMismatch
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def PropertyTypeMismatchStart(builder): builder.StartObject(0)
def Start(builder):
    return PropertyTypeMismatchStart(builder)
def PropertyTypeMismatchEnd(builder): return builder.EndObject()
def End(builder):
    return PropertyTypeMismatchEnd(builder)