# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PropDefs(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PropDefs()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPropDefs(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PropDefs
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PropDefs
    def Props(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorCommon.PropDef import PropDef
            obj = PropDef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PropDefs
    def PropsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # PropDefs
    def PropsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def PropDefsStart(builder):
    builder.StartObject(1)

def Start(builder):
    PropDefsStart(builder)

def PropDefsAddProps(builder, props):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(props), 0)

def AddProps(builder, props):
    PropDefsAddProps(builder, props)

def PropDefsStartPropsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartPropsVector(builder, numElems: int) -> int:
    return PropDefsStartPropsVector(builder, numElems)

def PropDefsEnd(builder):
    return builder.EndObject()

def End(builder):
    return PropDefsEnd(builder)
