# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RecursiveMove(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RecursiveMove()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRecursiveMove(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RecursiveMove
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RecursiveMove
    def FromObj(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RecursiveMove
    def ToObj(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RecursiveMoveStart(builder): builder.StartObject(2)
def Start(builder):
    return RecursiveMoveStart(builder)
def RecursiveMoveAddFromObj(builder, fromObj): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(fromObj), 0)
def AddFromObj(builder, fromObj):
    return RecursiveMoveAddFromObj(builder, fromObj)
def RecursiveMoveAddToObj(builder, toObj): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(toObj), 0)
def AddToObj(builder, toObj):
    return RecursiveMoveAddToObj(builder, toObj)
def RecursiveMoveEnd(builder): return builder.EndObject()
def End(builder):
    return RecursiveMoveEnd(builder)