# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TracebackEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TracebackEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTracebackEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TracebackEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TracebackEvent
    def Exception(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Exception import Exception
            obj = Exception()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def TracebackEventStart(builder): builder.StartObject(1)
def Start(builder):
    return TracebackEventStart(builder)
def TracebackEventAddException(builder, exception): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(exception), 0)
def AddException(builder, exception):
    return TracebackEventAddException(builder, exception)
def TracebackEventEnd(builder): return builder.EndObject()
def End(builder):
    return TracebackEventEnd(builder)