# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UnknownLoopLabel(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UnknownLoopLabel()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUnknownLoopLabel(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UnknownLoopLabel
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UnknownLoopLabel
    def Context(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.CompileContext import CompileContext
            obj = CompileContext()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # UnknownLoopLabel
    def Label(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def UnknownLoopLabelStart(builder): builder.StartObject(2)
def Start(builder):
    return UnknownLoopLabelStart(builder)
def UnknownLoopLabelAddContext(builder, context): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(context), 0)
def AddContext(builder, context):
    return UnknownLoopLabelAddContext(builder, context)
def UnknownLoopLabelAddLabel(builder, label): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(label), 0)
def AddLabel(builder, label):
    return UnknownLoopLabelAddLabel(builder, label)
def UnknownLoopLabelEnd(builder): return builder.EndObject()
def End(builder):
    return UnknownLoopLabelEnd(builder)