# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UnknownTypeConstant(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UnknownTypeConstant()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUnknownTypeConstant(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UnknownTypeConstant
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UnknownTypeConstant
    def Context(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.CompileContext import CompileContext
            obj = CompileContext()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # UnknownTypeConstant
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def UnknownTypeConstantStart(builder):
    builder.StartObject(2)

def Start(builder):
    UnknownTypeConstantStart(builder)

def UnknownTypeConstantAddContext(builder, context):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(context), 0)

def AddContext(builder, context):
    UnknownTypeConstantAddContext(builder, context)

def UnknownTypeConstantAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    UnknownTypeConstantAddName(builder, name)

def UnknownTypeConstantEnd(builder):
    return builder.EndObject()

def End(builder):
    return UnknownTypeConstantEnd(builder)
