# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class UnpresentEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = UnpresentEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsUnpresentEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # UnpresentEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # UnpresentEvent
    def PresentationId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def UnpresentEventStart(builder):
    builder.StartObject(1)

def Start(builder):
    UnpresentEventStart(builder)

def UnpresentEventAddPresentationId(builder, presentationId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(presentationId), 0)

def AddPresentationId(builder, presentationId):
    UnpresentEventAddPresentationId(builder, presentationId)

def UnpresentEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return UnpresentEventEnd(builder)
