# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VerbDefs(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VerbDefs()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVerbDefs(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VerbDefs
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VerbDefs
    def Verbs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorCommon.VerbDef import VerbDef
            obj = VerbDef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VerbDefs
    def VerbsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VerbDefs
    def VerbsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def VerbDefsStart(builder): builder.StartObject(1)
def Start(builder):
    return VerbDefsStart(builder)
def VerbDefsAddVerbs(builder, verbs): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(verbs), 0)
def AddVerbs(builder, verbs):
    return VerbDefsAddVerbs(builder, verbs)
def VerbDefsStartVerbsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartVerbsVector(builder, numElems):
    return VerbDefsStartVerbsVector(builder, numElems)
def VerbDefsEnd(builder): return builder.EndObject()
def End(builder):
    return VerbDefsEnd(builder)