# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VerbDecodeError(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VerbDecodeError()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVerbDecodeError(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VerbDecodeError
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VerbDecodeError
    def Obj(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VerbDecodeError
    def Verb(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Symbol import Symbol
            obj = Symbol()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def VerbDecodeErrorStart(builder): builder.StartObject(2)
def Start(builder):
    return VerbDecodeErrorStart(builder)
def VerbDecodeErrorAddObj(builder, obj): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(obj), 0)
def AddObj(builder, obj):
    return VerbDecodeErrorAddObj(builder, obj)
def VerbDecodeErrorAddVerb(builder, verb): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(verb), 0)
def AddVerb(builder, verb):
    return VerbDecodeErrorAddVerb(builder, verb)
def VerbDecodeErrorEnd(builder): return builder.EndObject()
def End(builder):
    return VerbDecodeErrorEnd(builder)