# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorCommon

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorldStateError(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorldStateError()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorldStateError(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorldStateError
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorldStateError
    def ErrorType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # WorldStateError
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def WorldStateErrorStart(builder):
    builder.StartObject(2)

def Start(builder):
    WorldStateErrorStart(builder)

def WorldStateErrorAddErrorType(builder, errorType):
    builder.PrependUint8Slot(0, errorType, 0)

def AddErrorType(builder, errorType):
    WorldStateErrorAddErrorType(builder, errorType)

def WorldStateErrorAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def AddError(builder, error):
    WorldStateErrorAddError(builder, error)

def WorldStateErrorEnd(builder):
    return builder.EndObject()

def End(builder):
    return WorldStateErrorEnd(builder)
