# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorEventLog

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class LoggedNarrativeEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = LoggedNarrativeEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsLoggedNarrativeEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # LoggedNarrativeEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # LoggedNarrativeEvent
    def Player(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # LoggedNarrativeEvent
    def Event(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.NarrativeEvent import NarrativeEvent
            obj = NarrativeEvent()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def LoggedNarrativeEventStart(builder):
    builder.StartObject(2)

def Start(builder):
    LoggedNarrativeEventStart(builder)

def LoggedNarrativeEventAddPlayer(builder, player):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(player), 0)

def AddPlayer(builder, player):
    LoggedNarrativeEventAddPlayer(builder, player)

def LoggedNarrativeEventAddEvent(builder, event):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(event), 0)

def AddEvent(builder, event):
    LoggedNarrativeEventAddEvent(builder, event)

def LoggedNarrativeEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return LoggedNarrativeEventEnd(builder)
