# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

class ClientEventUnion(object):
    NONE = 0
    NarrativeEventMessage = 1
    RequestInputEvent = 2
    SystemMessageEvent = 3
    DisconnectEvent = 4
    TaskErrorEvent = 5
    TaskSuccessEvent = 6
    PlayerSwitchedEvent = 7
    SetConnectionOptionEvent = 8
