# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ClientSuccess(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClientSuccess()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClientSuccess(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ClientSuccess
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClientSuccess
    def Reply(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.DaemonToClientReply import DaemonToClientReply
            obj = DaemonToClientReply()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def ClientSuccessStart(builder):
    builder.StartObject(1)

def Start(builder):
    ClientSuccessStart(builder)

def ClientSuccessAddReply(builder, reply):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(reply), 0)

def AddReply(builder, reply):
    ClientSuccessAddReply(builder, reply)

def ClientSuccessEnd(builder):
    return builder.EndObject()

def End(builder):
    return ClientSuccessEnd(builder)
