# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ClientsBroadcastPingPong(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClientsBroadcastPingPong()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClientsBroadcastPingPong(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ClientsBroadcastPingPong
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClientsBroadcastPingPong
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def ClientsBroadcastPingPongStart(builder): builder.StartObject(1)
def Start(builder):
    return ClientsBroadcastPingPongStart(builder)
def ClientsBroadcastPingPongAddTimestamp(builder, timestamp): builder.PrependUint64Slot(0, timestamp, 0)
def AddTimestamp(builder, timestamp):
    return ClientsBroadcastPingPongAddTimestamp(builder, timestamp)
def ClientsBroadcastPingPongEnd(builder): return builder.EndObject()
def End(builder):
    return ClientsBroadcastPingPongEnd(builder)