# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ClientAttributeSet(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClientAttributeSet()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClientAttributeSet(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ClientAttributeSet
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ClientAttributeSetStart(builder): builder.StartObject(0)
def Start(builder):
    return ClientAttributeSetStart(builder)
def ClientAttributeSetEnd(builder): return builder.EndObject()
def End(builder):
    return ClientAttributeSetEnd(builder)