# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ClientsBroadcastEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ClientsBroadcastEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsClientsBroadcastEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ClientsBroadcastEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ClientsBroadcastEvent
    def EventType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ClientsBroadcastEvent
    def Event(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def ClientsBroadcastEventStart(builder):
    builder.StartObject(2)

def Start(builder):
    ClientsBroadcastEventStart(builder)

def ClientsBroadcastEventAddEventType(builder, eventType):
    builder.PrependUint8Slot(0, eventType, 0)

def AddEventType(builder, eventType):
    ClientsBroadcastEventAddEventType(builder, eventType)

def ClientsBroadcastEventAddEvent(builder, event):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(event), 0)

def AddEvent(builder, event):
    ClientsBroadcastEventAddEvent(builder, event)

def ClientsBroadcastEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return ClientsBroadcastEventEnd(builder)
