# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

class CommandErrorUnion(object):
    NONE = 0
    CouldNotParseCommand = 1
    NoObjectMatch = 2
    NoCommandMatch = 3
    DatabaseError = 4
    PermissionDenied = 5
