# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CompilationError(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CompilationError()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCompilationError(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CompilationError
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CompilationError
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.CompileError import CompileError
            obj = CompileError()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def CompilationErrorStart(builder):
    builder.StartObject(1)

def Start(builder):
    CompilationErrorStart(builder)

def CompilationErrorAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def AddError(builder, error):
    CompilationErrorAddError(builder, error)

def CompilationErrorEnd(builder):
    return builder.EndObject()

def End(builder):
    return CompilationErrorEnd(builder)
