# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CompileContext(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CompileContext()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCompileContext(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CompileContext
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CompileContext
    def Line(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CompileContext
    def Col(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def CompileContextStart(builder): builder.StartObject(2)
def Start(builder):
    return CompileContextStart(builder)
def CompileContextAddLine(builder, line): builder.PrependUint64Slot(0, line, 0)
def AddLine(builder, line):
    return CompileContextAddLine(builder, line)
def CompileContextAddCol(builder, col): builder.PrependUint64Slot(1, col, 0)
def AddCol(builder, col):
    return CompileContextAddCol(builder, col)
def CompileContextEnd(builder): return builder.EndObject()
def End(builder):
    return CompileContextEnd(builder)