# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CouldNotParseCommand(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CouldNotParseCommand()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCouldNotParseCommand(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CouldNotParseCommand
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def CouldNotParseCommandStart(builder):
    builder.StartObject(0)

def Start(builder):
    CouldNotParseCommandStart(builder)

def CouldNotParseCommandEnd(builder):
    return builder.EndObject()

def End(builder):
    return CouldNotParseCommandEnd(builder)
