# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DaemonToWorkerReply(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DaemonToWorkerReply()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDaemonToWorkerReply(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DaemonToWorkerReply
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DaemonToWorkerReply
    def ReplyType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # DaemonToWorkerReply
    def Reply(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def DaemonToWorkerReplyStart(builder): builder.StartObject(2)
def Start(builder):
    return DaemonToWorkerReplyStart(builder)
def DaemonToWorkerReplyAddReplyType(builder, replyType): builder.PrependUint8Slot(0, replyType, 0)
def AddReplyType(builder, replyType):
    return DaemonToWorkerReplyAddReplyType(builder, replyType)
def DaemonToWorkerReplyAddReply(builder, reply): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(reply), 0)
def AddReply(builder, reply):
    return DaemonToWorkerReplyAddReply(builder, reply)
def DaemonToWorkerReplyEnd(builder): return builder.EndObject()
def End(builder):
    return DaemonToWorkerReplyEnd(builder)