# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

class DaemonToClientReplyUnion(object):
    NONE = 0
    NewConnection = 1
    LoginResult = 2
    AttachResult = 3
    SysPropValue = 4
    TaskSubmitted = 5
    InputThanks = 6
    EvalResult = 7
    ThanksPong = 8
    VerbsReply = 9
    PropertiesReply = 10
    VerbProgramResponseReply = 11
    PropertyValue = 12
    VerbValue = 13
    ResolveResult = 14
    HistoryResponseReply = 15
    CurrentPresentations = 16
    PresentationDismissed = 17
    ClientAttributeSet = 18
    Disconnected = 19
