# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

class DaemonToWorkerMessageUnion(object):
    NONE = 0
    PingWorkers = 1
    WorkerRequest = 2
    PleaseDie = 3
