# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

class DaemonToWorkerReplyUnion(object):
    NONE = 0
    WorkerAck = 1
    WorkerRejected = 2
    WorkerAttached = 3
    WorkerAuthFailed = 4
    WorkerInvalidPayload = 5
    WorkerUnknownRequest = 6
    WorkerNotRegistered = 7
