# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Detach(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Detach()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDetach(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Detach
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Detach
    def ClientToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.ClientToken import ClientToken
            obj = ClientToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Detach
    def Disconnected(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def DetachStart(builder): builder.StartObject(2)
def Start(builder):
    return DetachStart(builder)
def DetachAddClientToken(builder, clientToken): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clientToken), 0)
def AddClientToken(builder, clientToken):
    return DetachAddClientToken(builder, clientToken)
def DetachAddDisconnected(builder, disconnected): builder.PrependBoolSlot(1, disconnected, 0)
def AddDisconnected(builder, disconnected):
    return DetachAddDisconnected(builder, disconnected)
def DetachEnd(builder): return builder.EndObject()
def End(builder):
    return DetachEnd(builder)