# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DisconnectEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DisconnectEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDisconnectEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DisconnectEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def DisconnectEventStart(builder):
    builder.StartObject(0)

def Start(builder):
    DisconnectEventStart(builder)

def DisconnectEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return DisconnectEventEnd(builder)
