# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DismissPresentation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DismissPresentation()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDismissPresentation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DismissPresentation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DismissPresentation
    def ClientToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.ClientToken import ClientToken
            obj = ClientToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DismissPresentation
    def AuthToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.AuthToken import AuthToken
            obj = AuthToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DismissPresentation
    def PresentationId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DismissPresentationStart(builder):
    builder.StartObject(3)

def Start(builder):
    DismissPresentationStart(builder)

def DismissPresentationAddClientToken(builder, clientToken):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clientToken), 0)

def AddClientToken(builder, clientToken):
    DismissPresentationAddClientToken(builder, clientToken)

def DismissPresentationAddAuthToken(builder, authToken):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(authToken), 0)

def AddAuthToken(builder, authToken):
    DismissPresentationAddAuthToken(builder, authToken)

def DismissPresentationAddPresentationId(builder, presentationId):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(presentationId), 0)

def AddPresentationId(builder, presentationId):
    DismissPresentationAddPresentationId(builder, presentationId)

def DismissPresentationEnd(builder):
    return builder.EndObject()

def End(builder):
    return DismissPresentationEnd(builder)
