# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EnrollmentResponse(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EnrollmentResponse()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEnrollmentResponse(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EnrollmentResponse
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EnrollmentResponse
    def Success(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # EnrollmentResponse
    def ServiceUuid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EnrollmentResponse
    def DaemonCurvePublicKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # EnrollmentResponse
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def EnrollmentResponseStart(builder): builder.StartObject(4)
def Start(builder):
    return EnrollmentResponseStart(builder)
def EnrollmentResponseAddSuccess(builder, success): builder.PrependBoolSlot(0, success, 0)
def AddSuccess(builder, success):
    return EnrollmentResponseAddSuccess(builder, success)
def EnrollmentResponseAddServiceUuid(builder, serviceUuid): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(serviceUuid), 0)
def AddServiceUuid(builder, serviceUuid):
    return EnrollmentResponseAddServiceUuid(builder, serviceUuid)
def EnrollmentResponseAddDaemonCurvePublicKey(builder, daemonCurvePublicKey): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(daemonCurvePublicKey), 0)
def AddDaemonCurvePublicKey(builder, daemonCurvePublicKey):
    return EnrollmentResponseAddDaemonCurvePublicKey(builder, daemonCurvePublicKey)
def EnrollmentResponseAddError(builder, error): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)
def AddError(builder, error):
    return EnrollmentResponseAddError(builder, error)
def EnrollmentResponseEnd(builder): return builder.EndObject()
def End(builder):
    return EnrollmentResponseEnd(builder)