# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EventLogPublicKey(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EventLogPublicKey()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEventLogPublicKey(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EventLogPublicKey
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EventLogPublicKey
    def PublicKey(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def EventLogPublicKeyStart(builder): builder.StartObject(1)
def Start(builder):
    return EventLogPublicKeyStart(builder)
def EventLogPublicKeyAddPublicKey(builder, publicKey): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(publicKey), 0)
def AddPublicKey(builder, publicKey):
    return EventLogPublicKeyAddPublicKey(builder, publicKey)
def EventLogPublicKeyEnd(builder): return builder.EndObject()
def End(builder):
    return EventLogPublicKeyEnd(builder)