# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HistoryRecallUntilEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HistoryRecallUntilEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHistoryRecallUntilEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HistoryRecallUntilEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HistoryRecallUntilEvent
    def EventId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Uuid import Uuid
            obj = Uuid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HistoryRecallUntilEvent
    def Limit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def HistoryRecallUntilEventStart(builder): builder.StartObject(2)
def Start(builder):
    return HistoryRecallUntilEventStart(builder)
def HistoryRecallUntilEventAddEventId(builder, eventId): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(eventId), 0)
def AddEventId(builder, eventId):
    return HistoryRecallUntilEventAddEventId(builder, eventId)
def HistoryRecallUntilEventAddLimit(builder, limit): builder.PrependUint64Slot(1, limit, 0)
def AddLimit(builder, limit):
    return HistoryRecallUntilEventAddLimit(builder, limit)
def HistoryRecallUntilEventEnd(builder): return builder.EndObject()
def End(builder):
    return HistoryRecallUntilEventEnd(builder)