# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HostToDaemonMsg(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HostToDaemonMsg()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHostToDaemonMsg(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HostToDaemonMsg
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HostToDaemonMsg
    def HostToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.HostToken import HostToken
            obj = HostToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HostToDaemonMsg
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.HostToDaemonMessage import HostToDaemonMessage
            obj = HostToDaemonMessage()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def HostToDaemonMsgStart(builder):
    builder.StartObject(2)

def Start(builder):
    HostToDaemonMsgStart(builder)

def HostToDaemonMsgAddHostToken(builder, hostToken):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(hostToken), 0)

def AddHostToken(builder, hostToken):
    HostToDaemonMsgAddHostToken(builder, hostToken)

def HostToDaemonMsgAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    HostToDaemonMsgAddMessage(builder, message)

def HostToDaemonMsgEnd(builder):
    return builder.EndObject()

def End(builder):
    return HostToDaemonMsgEnd(builder)
