# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HostSuccess(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HostSuccess()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHostSuccess(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HostSuccess
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HostSuccess
    def Reply(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.DaemonToHostReply import DaemonToHostReply
            obj = DaemonToHostReply()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def HostSuccessStart(builder): builder.StartObject(1)
def Start(builder):
    return HostSuccessStart(builder)
def HostSuccessAddReply(builder, reply): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(reply), 0)
def AddReply(builder, reply):
    return HostSuccessAddReply(builder, reply)
def HostSuccessEnd(builder): return builder.EndObject()
def End(builder):
    return HostSuccessEnd(builder)