# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HostToken(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HostToken()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHostToken(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HostToken
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HostToken
    def Token(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def HostTokenStart(builder):
    builder.StartObject(1)

def Start(builder):
    HostTokenStart(builder)

def HostTokenAddToken(builder, token):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(token), 0)

def AddToken(builder, token):
    HostTokenAddToken(builder, token)

def HostTokenEnd(builder):
    return builder.EndObject()

def End(builder):
    return HostTokenEnd(builder)
