# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HostToDaemonMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HostToDaemonMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHostToDaemonMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HostToDaemonMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HostToDaemonMessage
    def MessageType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # HostToDaemonMessage
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def HostToDaemonMessageStart(builder): builder.StartObject(2)
def Start(builder):
    return HostToDaemonMessageStart(builder)
def HostToDaemonMessageAddMessageType(builder, messageType): builder.PrependUint8Slot(0, messageType, 0)
def AddMessageType(builder, messageType):
    return HostToDaemonMessageAddMessageType(builder, messageType)
def HostToDaemonMessageAddMessage(builder, message): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)
def AddMessage(builder, message):
    return HostToDaemonMessageAddMessage(builder, message)
def HostToDaemonMessageEnd(builder): return builder.EndObject()
def End(builder):
    return HostToDaemonMessageEnd(builder)