# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HostBroadcastPingPong(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HostBroadcastPingPong()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHostBroadcastPingPong(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HostBroadcastPingPong
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HostBroadcastPingPong
    def Timestamp(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def HostBroadcastPingPongStart(builder): builder.StartObject(1)
def Start(builder):
    return HostBroadcastPingPongStart(builder)
def HostBroadcastPingPongAddTimestamp(builder, timestamp): builder.PrependUint64Slot(0, timestamp, 0)
def AddTimestamp(builder, timestamp):
    return HostBroadcastPingPongAddTimestamp(builder, timestamp)
def HostBroadcastPingPongEnd(builder): return builder.EndObject()
def End(builder):
    return HostBroadcastPingPongEnd(builder)