# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class HostBroadcastListen(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HostBroadcastListen()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHostBroadcastListen(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HostBroadcastListen
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HostBroadcastListen
    def HandlerObject(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # HostBroadcastListen
    def HostType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # HostBroadcastListen
    def Port(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # HostBroadcastListen
    def PrintMessages(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def HostBroadcastListenStart(builder):
    builder.StartObject(4)

def Start(builder):
    HostBroadcastListenStart(builder)

def HostBroadcastListenAddHandlerObject(builder, handlerObject):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(handlerObject), 0)

def AddHandlerObject(builder, handlerObject):
    HostBroadcastListenAddHandlerObject(builder, handlerObject)

def HostBroadcastListenAddHostType(builder, hostType):
    builder.PrependUint8Slot(1, hostType, 0)

def AddHostType(builder, hostType):
    HostBroadcastListenAddHostType(builder, hostType)

def HostBroadcastListenAddPort(builder, port):
    builder.PrependUint16Slot(2, port, 0)

def AddPort(builder, port):
    HostBroadcastListenAddPort(builder, port)

def HostBroadcastListenAddPrintMessages(builder, printMessages):
    builder.PrependBoolSlot(3, printMessages, 0)

def AddPrintMessages(builder, printMessages):
    HostBroadcastListenAddPrintMessages(builder, printMessages)

def HostBroadcastListenEnd(builder):
    return builder.EndObject()

def End(builder):
    return HostBroadcastListenEnd(builder)
