# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

class HostClientToDaemonMessageUnion(object):
    NONE = 0
    ConnectionEstablish = 1
    RequestSysProp = 2
    LoginCommand = 3
    Attach = 4
    Command = 5
    Verbs = 6
    InvokeVerb = 7
    Properties = 8
    Retrieve = 9
    Program = 10
    RequestedInput = 11
    OutOfBand = 12
    Eval = 13
    Resolve = 14
    ClientPong = 15
    RequestHistory = 16
    RequestCurrentPresentations = 17
    DismissPresentation = 18
    SetClientAttribute = 19
    Detach = 20
