# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class InvokeSystemHandler(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InvokeSystemHandler()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInvokeSystemHandler(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InvokeSystemHandler
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InvokeSystemHandler
    def HostId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Uuid import Uuid
            obj = Uuid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InvokeSystemHandler
    def HandlerType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # InvokeSystemHandler
    def Args(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorVar.Var import Var
            obj = Var()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InvokeSystemHandler
    def ArgsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InvokeSystemHandler
    def ArgsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # InvokeSystemHandler
    def AuthToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.AuthToken import AuthToken
            obj = AuthToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def InvokeSystemHandlerStart(builder): builder.StartObject(4)
def Start(builder):
    return InvokeSystemHandlerStart(builder)
def InvokeSystemHandlerAddHostId(builder, hostId): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(hostId), 0)
def AddHostId(builder, hostId):
    return InvokeSystemHandlerAddHostId(builder, hostId)
def InvokeSystemHandlerAddHandlerType(builder, handlerType): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(handlerType), 0)
def AddHandlerType(builder, handlerType):
    return InvokeSystemHandlerAddHandlerType(builder, handlerType)
def InvokeSystemHandlerAddArgs(builder, args): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(args), 0)
def AddArgs(builder, args):
    return InvokeSystemHandlerAddArgs(builder, args)
def InvokeSystemHandlerStartArgsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartArgsVector(builder, numElems):
    return InvokeSystemHandlerStartArgsVector(builder, numElems)
def InvokeSystemHandlerAddAuthToken(builder, authToken): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(authToken), 0)
def AddAuthToken(builder, authToken):
    return InvokeSystemHandlerAddAuthToken(builder, authToken)
def InvokeSystemHandlerEnd(builder): return builder.EndObject()
def End(builder):
    return InvokeSystemHandlerEnd(builder)