# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ObjectInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ObjectInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsObjectInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ObjectInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ObjectInfo
    def Obj(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ObjectInfo
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Symbol import Symbol
            obj = Symbol()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ObjectInfo
    def Parent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ObjectInfo
    def Owner(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ObjectInfo
    def Flags(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # ObjectInfo
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ObjectInfo
    def ContentsCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ObjectInfo
    def VerbsCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # ObjectInfo
    def PropertiesCount(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def ObjectInfoStart(builder): builder.StartObject(9)
def Start(builder):
    return ObjectInfoStart(builder)
def ObjectInfoAddObj(builder, obj): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(obj), 0)
def AddObj(builder, obj):
    return ObjectInfoAddObj(builder, obj)
def ObjectInfoAddName(builder, name): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def AddName(builder, name):
    return ObjectInfoAddName(builder, name)
def ObjectInfoAddParent(builder, parent): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(parent), 0)
def AddParent(builder, parent):
    return ObjectInfoAddParent(builder, parent)
def ObjectInfoAddOwner(builder, owner): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(owner), 0)
def AddOwner(builder, owner):
    return ObjectInfoAddOwner(builder, owner)
def ObjectInfoAddFlags(builder, flags): builder.PrependUint16Slot(4, flags, 0)
def AddFlags(builder, flags):
    return ObjectInfoAddFlags(builder, flags)
def ObjectInfoAddLocation(builder, location): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(location), 0)
def AddLocation(builder, location):
    return ObjectInfoAddLocation(builder, location)
def ObjectInfoAddContentsCount(builder, contentsCount): builder.PrependUint32Slot(6, contentsCount, 0)
def AddContentsCount(builder, contentsCount):
    return ObjectInfoAddContentsCount(builder, contentsCount)
def ObjectInfoAddVerbsCount(builder, verbsCount): builder.PrependUint32Slot(7, verbsCount, 0)
def AddVerbsCount(builder, verbsCount):
    return ObjectInfoAddVerbsCount(builder, verbsCount)
def ObjectInfoAddPropertiesCount(builder, propertiesCount): builder.PrependUint32Slot(8, propertiesCount, 0)
def AddPropertiesCount(builder, propertiesCount):
    return ObjectInfoAddPropertiesCount(builder, propertiesCount)
def ObjectInfoEnd(builder): return builder.EndObject()
def End(builder):
    return ObjectInfoEnd(builder)