# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PlayerSwitchedEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PlayerSwitchedEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPlayerSwitchedEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PlayerSwitchedEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PlayerSwitchedEvent
    def NewPlayer(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PlayerSwitchedEvent
    def NewAuthToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.AuthToken import AuthToken
            obj = AuthToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def PlayerSwitchedEventStart(builder):
    builder.StartObject(2)

def Start(builder):
    PlayerSwitchedEventStart(builder)

def PlayerSwitchedEventAddNewPlayer(builder, newPlayer):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(newPlayer), 0)

def AddNewPlayer(builder, newPlayer):
    PlayerSwitchedEventAddNewPlayer(builder, newPlayer)

def PlayerSwitchedEventAddNewAuthToken(builder, newAuthToken):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(newAuthToken), 0)

def AddNewAuthToken(builder, newAuthToken):
    PlayerSwitchedEventAddNewAuthToken(builder, newAuthToken)

def PlayerSwitchedEventEnd(builder):
    return builder.EndObject()

def End(builder):
    return PlayerSwitchedEventEnd(builder)
