# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PropertyValue(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PropertyValue()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPropertyValue(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PropertyValue
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PropertyValue
    def PropInfo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.PropInfo import PropInfo
            obj = PropInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # PropertyValue
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorVar.Var import Var
            obj = Var()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def PropertyValueStart(builder): builder.StartObject(2)
def Start(builder):
    return PropertyValueStart(builder)
def PropertyValueAddPropInfo(builder, propInfo): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(propInfo), 0)
def AddPropInfo(builder, propInfo):
    return PropertyValueAddPropInfo(builder, propInfo)
def PropertyValueAddValue(builder, value): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)
def AddValue(builder, value):
    return PropertyValueAddValue(builder, value)
def PropertyValueEnd(builder): return builder.EndObject()
def End(builder):
    return PropertyValueEnd(builder)