# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PropertyRetrievalFailed(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PropertyRetrievalFailed()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPropertyRetrievalFailed(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PropertyRetrievalFailed
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PropertyRetrievalFailed
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.WorldStateError import WorldStateError
            obj = WorldStateError()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def PropertyRetrievalFailedStart(builder):
    builder.StartObject(1)

def Start(builder):
    PropertyRetrievalFailedStart(builder)

def PropertyRetrievalFailedAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def AddError(builder, error):
    PropertyRetrievalFailedAddError(builder, error)

def PropertyRetrievalFailedEnd(builder):
    return builder.EndObject()

def End(builder):
    return PropertyRetrievalFailedEnd(builder)
