# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Reattach(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Reattach()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReattach(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Reattach
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Reattach
    def ClientToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.ClientToken import ClientToken
            obj = ClientToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Reattach
    def AuthToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.AuthToken import AuthToken
            obj = AuthToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Reattach
    def PeerAddr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Reattach
    def LocalPort(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Reattach
    def RemotePort(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

    # Reattach
    def AcceptableContentTypes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorCommon.Symbol import Symbol
            obj = Symbol()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Reattach
    def AcceptableContentTypesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Reattach
    def AcceptableContentTypesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Reattach
    def ConnectionAttributes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorRpc.ConnectionAttribute import ConnectionAttribute
            obj = ConnectionAttribute()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Reattach
    def ConnectionAttributesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Reattach
    def ConnectionAttributesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

def ReattachStart(builder): builder.StartObject(7)
def Start(builder):
    return ReattachStart(builder)
def ReattachAddClientToken(builder, clientToken): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clientToken), 0)
def AddClientToken(builder, clientToken):
    return ReattachAddClientToken(builder, clientToken)
def ReattachAddAuthToken(builder, authToken): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(authToken), 0)
def AddAuthToken(builder, authToken):
    return ReattachAddAuthToken(builder, authToken)
def ReattachAddPeerAddr(builder, peerAddr): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(peerAddr), 0)
def AddPeerAddr(builder, peerAddr):
    return ReattachAddPeerAddr(builder, peerAddr)
def ReattachAddLocalPort(builder, localPort): builder.PrependUint16Slot(3, localPort, 0)
def AddLocalPort(builder, localPort):
    return ReattachAddLocalPort(builder, localPort)
def ReattachAddRemotePort(builder, remotePort): builder.PrependUint16Slot(4, remotePort, 0)
def AddRemotePort(builder, remotePort):
    return ReattachAddRemotePort(builder, remotePort)
def ReattachAddAcceptableContentTypes(builder, acceptableContentTypes): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(acceptableContentTypes), 0)
def AddAcceptableContentTypes(builder, acceptableContentTypes):
    return ReattachAddAcceptableContentTypes(builder, acceptableContentTypes)
def ReattachStartAcceptableContentTypesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartAcceptableContentTypesVector(builder, numElems):
    return ReattachStartAcceptableContentTypesVector(builder, numElems)
def ReattachAddConnectionAttributes(builder, connectionAttributes): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(connectionAttributes), 0)
def AddConnectionAttributes(builder, connectionAttributes):
    return ReattachAddConnectionAttributes(builder, connectionAttributes)
def ReattachStartConnectionAttributesVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartConnectionAttributesVector(builder, numElems):
    return ReattachStartConnectionAttributesVector(builder, numElems)
def ReattachEnd(builder): return builder.EndObject()
def End(builder):
    return ReattachEnd(builder)