# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ReplyResult(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReplyResult()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReplyResult(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReplyResult
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReplyResult
    def ResultType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ReplyResult
    def Result(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def ReplyResultStart(builder):
    builder.StartObject(2)

def Start(builder):
    ReplyResultStart(builder)

def ReplyResultAddResultType(builder, resultType):
    builder.PrependUint8Slot(0, resultType, 0)

def AddResultType(builder, resultType):
    ReplyResultAddResultType(builder, resultType)

def ReplyResultAddResult(builder, result):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)

def AddResult(builder, result):
    ReplyResultAddResult(builder, result)

def ReplyResultEnd(builder):
    return builder.EndObject()

def End(builder):
    return ReplyResultEnd(builder)
