# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RequestCurrentPresentations(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RequestCurrentPresentations()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequestCurrentPresentations(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RequestCurrentPresentations
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RequestCurrentPresentations
    def AuthToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.AuthToken import AuthToken
            obj = AuthToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RequestCurrentPresentationsStart(builder): builder.StartObject(1)
def Start(builder):
    return RequestCurrentPresentationsStart(builder)
def RequestCurrentPresentationsAddAuthToken(builder, authToken): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(authToken), 0)
def AddAuthToken(builder, authToken):
    return RequestCurrentPresentationsAddAuthToken(builder, authToken)
def RequestCurrentPresentationsEnd(builder): return builder.EndObject()
def End(builder):
    return RequestCurrentPresentationsEnd(builder)