# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RequestHistory(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RequestHistory()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequestHistory(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RequestHistory
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RequestHistory
    def ClientToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.ClientToken import ClientToken
            obj = ClientToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RequestHistory
    def AuthToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.AuthToken import AuthToken
            obj = AuthToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RequestHistory
    def HistoryRecall(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.HistoryRecall import HistoryRecall
            obj = HistoryRecall()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RequestHistoryStart(builder):
    builder.StartObject(3)

def Start(builder):
    RequestHistoryStart(builder)

def RequestHistoryAddClientToken(builder, clientToken):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clientToken), 0)

def AddClientToken(builder, clientToken):
    RequestHistoryAddClientToken(builder, clientToken)

def RequestHistoryAddAuthToken(builder, authToken):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(authToken), 0)

def AddAuthToken(builder, authToken):
    RequestHistoryAddAuthToken(builder, authToken)

def RequestHistoryAddHistoryRecall(builder, historyRecall):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(historyRecall), 0)

def AddHistoryRecall(builder, historyRecall):
    RequestHistoryAddHistoryRecall(builder, historyRecall)

def RequestHistoryEnd(builder):
    return builder.EndObject()

def End(builder):
    return RequestHistoryEnd(builder)
