# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RequestError(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RequestError()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequestError(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RequestError
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RequestError
    def Token(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.WorkerToken import WorkerToken
            obj = WorkerToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RequestError
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Uuid import Uuid
            obj = Uuid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RequestError
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.WorkerError import WorkerError
            obj = WorkerError()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RequestErrorStart(builder):
    builder.StartObject(3)

def Start(builder):
    RequestErrorStart(builder)

def RequestErrorAddToken(builder, token):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(token), 0)

def AddToken(builder, token):
    RequestErrorAddToken(builder, token)

def RequestErrorAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    RequestErrorAddId(builder, id)

def RequestErrorAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def AddError(builder, error):
    RequestErrorAddError(builder, error)

def RequestErrorEnd(builder):
    return builder.EndObject()

def End(builder):
    return RequestErrorEnd(builder)
