# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class RequestError(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = RequestError()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRequestError(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # RequestError
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # RequestError
    def WorkerId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Uuid import Uuid
            obj = Uuid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RequestError
    def RequestId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Uuid import Uuid
            obj = Uuid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # RequestError
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.WorkerError import WorkerError
            obj = WorkerError()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def RequestErrorStart(builder): builder.StartObject(3)
def Start(builder):
    return RequestErrorStart(builder)
def RequestErrorAddWorkerId(builder, workerId): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(workerId), 0)
def AddWorkerId(builder, workerId):
    return RequestErrorAddWorkerId(builder, workerId)
def RequestErrorAddRequestId(builder, requestId): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(requestId), 0)
def AddRequestId(builder, requestId):
    return RequestErrorAddRequestId(builder, requestId)
def RequestErrorAddError(builder, error): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)
def AddError(builder, error):
    return RequestErrorAddError(builder, error)
def RequestErrorEnd(builder): return builder.EndObject()
def End(builder):
    return RequestErrorEnd(builder)