# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

class SchedulerErrorUnion(object):
    NONE = 0
    SchedulerNotResponding = 1
    TaskNotFound = 2
    InputRequestNotFound = 3
    CouldNotStartTask = 4
    CompilationError = 5
    CommandExecutionError = 6
    TaskAbortedLimit = 7
    TaskAbortedError = 8
    TaskAbortedException = 9
    TaskAbortedCancelled = 10
    VerbProgramFailed = 11
    PropertyRetrievalFailed = 12
    VerbRetrievalFailed = 13
    ObjectResolutionFailed = 14
    GarbageCollectionFailed = 15
