# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

class SchedulerErrorUnion(object):
    NONE = 0
    SchedulerNotResponding = 1
    TaskNotFound = 2
    InputRequestNotFound = 3
    CouldNotStartTask = 4
    CompilationError = 5
    CommandExecutionError = 6
    TaskAbortedLimit = 7
    TaskAbortedError = 8
    TaskAbortedVerbNotFound = 9
    TaskAbortedException = 10
    TaskAbortedCancelled = 11
    VerbProgramFailed = 12
    PropertyRetrievalFailed = 13
    VerbRetrievalFailed = 14
    ObjectResolutionFailed = 15
    GarbageCollectionFailed = 16
