# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ServerFeatures(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ServerFeatures()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsServerFeatures(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ServerFeatures
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ServerFeatures
    def PersistentTasks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServerFeatures
    def RichNotify(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServerFeatures
    def LexicalScopes(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServerFeatures
    def TypeDispatch(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServerFeatures
    def FlyweightType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServerFeatures
    def ListComprehensions(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServerFeatures
    def BoolType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServerFeatures
    def UseBooleanReturns(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServerFeatures
    def SymbolType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServerFeatures
    def UseSymbolsInBuiltins(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServerFeatures
    def CustomErrors(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(24))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServerFeatures
    def UseUuobjids(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(26))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServerFeatures
    def EnableEventlog(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(28))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # ServerFeatures
    def AnonymousObjects(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(30))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def ServerFeaturesStart(builder): builder.StartObject(14)
def Start(builder):
    return ServerFeaturesStart(builder)
def ServerFeaturesAddPersistentTasks(builder, persistentTasks): builder.PrependBoolSlot(0, persistentTasks, 0)
def AddPersistentTasks(builder, persistentTasks):
    return ServerFeaturesAddPersistentTasks(builder, persistentTasks)
def ServerFeaturesAddRichNotify(builder, richNotify): builder.PrependBoolSlot(1, richNotify, 0)
def AddRichNotify(builder, richNotify):
    return ServerFeaturesAddRichNotify(builder, richNotify)
def ServerFeaturesAddLexicalScopes(builder, lexicalScopes): builder.PrependBoolSlot(2, lexicalScopes, 0)
def AddLexicalScopes(builder, lexicalScopes):
    return ServerFeaturesAddLexicalScopes(builder, lexicalScopes)
def ServerFeaturesAddTypeDispatch(builder, typeDispatch): builder.PrependBoolSlot(3, typeDispatch, 0)
def AddTypeDispatch(builder, typeDispatch):
    return ServerFeaturesAddTypeDispatch(builder, typeDispatch)
def ServerFeaturesAddFlyweightType(builder, flyweightType): builder.PrependBoolSlot(4, flyweightType, 0)
def AddFlyweightType(builder, flyweightType):
    return ServerFeaturesAddFlyweightType(builder, flyweightType)
def ServerFeaturesAddListComprehensions(builder, listComprehensions): builder.PrependBoolSlot(5, listComprehensions, 0)
def AddListComprehensions(builder, listComprehensions):
    return ServerFeaturesAddListComprehensions(builder, listComprehensions)
def ServerFeaturesAddBoolType(builder, boolType): builder.PrependBoolSlot(6, boolType, 0)
def AddBoolType(builder, boolType):
    return ServerFeaturesAddBoolType(builder, boolType)
def ServerFeaturesAddUseBooleanReturns(builder, useBooleanReturns): builder.PrependBoolSlot(7, useBooleanReturns, 0)
def AddUseBooleanReturns(builder, useBooleanReturns):
    return ServerFeaturesAddUseBooleanReturns(builder, useBooleanReturns)
def ServerFeaturesAddSymbolType(builder, symbolType): builder.PrependBoolSlot(8, symbolType, 0)
def AddSymbolType(builder, symbolType):
    return ServerFeaturesAddSymbolType(builder, symbolType)
def ServerFeaturesAddUseSymbolsInBuiltins(builder, useSymbolsInBuiltins): builder.PrependBoolSlot(9, useSymbolsInBuiltins, 0)
def AddUseSymbolsInBuiltins(builder, useSymbolsInBuiltins):
    return ServerFeaturesAddUseSymbolsInBuiltins(builder, useSymbolsInBuiltins)
def ServerFeaturesAddCustomErrors(builder, customErrors): builder.PrependBoolSlot(10, customErrors, 0)
def AddCustomErrors(builder, customErrors):
    return ServerFeaturesAddCustomErrors(builder, customErrors)
def ServerFeaturesAddUseUuobjids(builder, useUuobjids): builder.PrependBoolSlot(11, useUuobjids, 0)
def AddUseUuobjids(builder, useUuobjids):
    return ServerFeaturesAddUseUuobjids(builder, useUuobjids)
def ServerFeaturesAddEnableEventlog(builder, enableEventlog): builder.PrependBoolSlot(12, enableEventlog, 0)
def AddEnableEventlog(builder, enableEventlog):
    return ServerFeaturesAddEnableEventlog(builder, enableEventlog)
def ServerFeaturesAddAnonymousObjects(builder, anonymousObjects): builder.PrependBoolSlot(13, anonymousObjects, 0)
def AddAnonymousObjects(builder, anonymousObjects):
    return ServerFeaturesAddAnonymousObjects(builder, anonymousObjects)
def ServerFeaturesEnd(builder): return builder.EndObject()
def End(builder):
    return ServerFeaturesEnd(builder)