# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SetConnectionOptionEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SetConnectionOptionEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSetConnectionOptionEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SetConnectionOptionEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SetConnectionOptionEvent
    def ConnectionObj(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SetConnectionOptionEvent
    def OptionName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Symbol import Symbol
            obj = Symbol()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SetConnectionOptionEvent
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorVar.Var import Var
            obj = Var()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SetConnectionOptionEventStart(builder): builder.StartObject(3)
def Start(builder):
    return SetConnectionOptionEventStart(builder)
def SetConnectionOptionEventAddConnectionObj(builder, connectionObj): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(connectionObj), 0)
def AddConnectionObj(builder, connectionObj):
    return SetConnectionOptionEventAddConnectionObj(builder, connectionObj)
def SetConnectionOptionEventAddOptionName(builder, optionName): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(optionName), 0)
def AddOptionName(builder, optionName):
    return SetConnectionOptionEventAddOptionName(builder, optionName)
def SetConnectionOptionEventAddValue(builder, value): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)
def AddValue(builder, value):
    return SetConnectionOptionEventAddValue(builder, value)
def SetConnectionOptionEventEnd(builder): return builder.EndObject()
def End(builder):
    return SetConnectionOptionEventEnd(builder)