# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SysPropValue(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SysPropValue()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSysPropValue(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SysPropValue
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SysPropValue
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorVar.Var import Var
            obj = Var()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SysPropValueStart(builder):
    builder.StartObject(1)

def Start(builder):
    SysPropValueStart(builder)

def SysPropValueAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    SysPropValueAddValue(builder, value)

def SysPropValueEnd(builder):
    return builder.EndObject()

def End(builder):
    return SysPropValueEnd(builder)
