# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SystemVerbResponseReply(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SystemVerbResponseReply()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSystemVerbResponseReply(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SystemVerbResponseReply
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SystemVerbResponseReply
    def ResponseType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # SystemVerbResponseReply
    def Response(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def SystemVerbResponseReplyStart(builder): builder.StartObject(2)
def Start(builder):
    return SystemVerbResponseReplyStart(builder)
def SystemVerbResponseReplyAddResponseType(builder, responseType): builder.PrependUint8Slot(0, responseType, 0)
def AddResponseType(builder, responseType):
    return SystemVerbResponseReplyAddResponseType(builder, responseType)
def SystemVerbResponseReplyAddResponse(builder, response): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(response), 0)
def AddResponse(builder, response):
    return SystemVerbResponseReplyAddResponse(builder, response)
def SystemVerbResponseReplyEnd(builder): return builder.EndObject()
def End(builder):
    return SystemVerbResponseReplyEnd(builder)