# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SystemVerbSuccess(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SystemVerbSuccess()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSystemVerbSuccess(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # SystemVerbSuccess
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SystemVerbSuccess
    def Result(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorVar.Var import Var
            obj = Var()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SystemVerbSuccess
    def Output(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorCommon.NarrativeEvent import NarrativeEvent
            obj = NarrativeEvent()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SystemVerbSuccess
    def OutputLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SystemVerbSuccess
    def OutputIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def SystemVerbSuccessStart(builder): builder.StartObject(2)
def Start(builder):
    return SystemVerbSuccessStart(builder)
def SystemVerbSuccessAddResult(builder, result): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)
def AddResult(builder, result):
    return SystemVerbSuccessAddResult(builder, result)
def SystemVerbSuccessAddOutput(builder, output): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(output), 0)
def AddOutput(builder, output):
    return SystemVerbSuccessAddOutput(builder, output)
def SystemVerbSuccessStartOutputVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartOutputVector(builder, numElems):
    return SystemVerbSuccessStartOutputVector(builder, numElems)
def SystemVerbSuccessEnd(builder): return builder.EndObject()
def End(builder):
    return SystemVerbSuccessEnd(builder)