# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TaskAbortedLimit(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TaskAbortedLimit()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTaskAbortedLimit(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TaskAbortedLimit
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TaskAbortedLimit
    def Limit(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.AbortLimit import AbortLimit
            obj = AbortLimit()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def TaskAbortedLimitStart(builder): builder.StartObject(1)
def Start(builder):
    return TaskAbortedLimitStart(builder)
def TaskAbortedLimitAddLimit(builder, limit): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(limit), 0)
def AddLimit(builder, limit):
    return TaskAbortedLimitAddLimit(builder, limit)
def TaskAbortedLimitEnd(builder): return builder.EndObject()
def End(builder):
    return TaskAbortedLimitEnd(builder)