# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TaskSuspendedEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TaskSuspendedEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTaskSuspendedEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TaskSuspendedEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TaskSuspendedEvent
    def TaskId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def TaskSuspendedEventStart(builder): builder.StartObject(1)
def Start(builder):
    return TaskSuspendedEventStart(builder)
def TaskSuspendedEventAddTaskId(builder, taskId): builder.PrependUint64Slot(0, taskId, 0)
def AddTaskId(builder, taskId):
    return TaskSuspendedEventAddTaskId(builder, taskId)
def TaskSuspendedEventEnd(builder): return builder.EndObject()
def End(builder):
    return TaskSuspendedEventEnd(builder)