# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class TaskSuccessEvent(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = TaskSuccessEvent()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTaskSuccessEvent(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # TaskSuccessEvent
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # TaskSuccessEvent
    def TaskId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # TaskSuccessEvent
    def Result(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorVar.Var import Var
            obj = Var()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def TaskSuccessEventStart(builder): builder.StartObject(2)
def Start(builder):
    return TaskSuccessEventStart(builder)
def TaskSuccessEventAddTaskId(builder, taskId): builder.PrependUint64Slot(0, taskId, 0)
def AddTaskId(builder, taskId):
    return TaskSuccessEventAddTaskId(builder, taskId)
def TaskSuccessEventAddResult(builder, result): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)
def AddResult(builder, result):
    return TaskSuccessEventAddResult(builder, result)
def TaskSuccessEventEnd(builder): return builder.EndObject()
def End(builder):
    return TaskSuccessEventEnd(builder)