# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VerbRetrievalFailed(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VerbRetrievalFailed()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVerbRetrievalFailed(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VerbRetrievalFailed
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VerbRetrievalFailed
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.WorldStateError import WorldStateError
            obj = WorldStateError()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def VerbRetrievalFailedStart(builder): builder.StartObject(1)
def Start(builder):
    return VerbRetrievalFailedStart(builder)
def VerbRetrievalFailedAddError(builder, error): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)
def AddError(builder, error):
    return VerbRetrievalFailedAddError(builder, error)
def VerbRetrievalFailedEnd(builder): return builder.EndObject()
def End(builder):
    return VerbRetrievalFailedEnd(builder)