# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Verbs(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Verbs()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVerbs(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Verbs
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Verbs
    def ClientToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.ClientToken import ClientToken
            obj = ClientToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Verbs
    def AuthToken(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.AuthToken import AuthToken
            obj = AuthToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Verbs
    def Object(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.ObjectRef import ObjectRef
            obj = ObjectRef()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Verbs
    def Inherited(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def VerbsStart(builder):
    builder.StartObject(4)

def Start(builder):
    VerbsStart(builder)

def VerbsAddClientToken(builder, clientToken):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(clientToken), 0)

def AddClientToken(builder, clientToken):
    VerbsAddClientToken(builder, clientToken)

def VerbsAddAuthToken(builder, authToken):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(authToken), 0)

def AddAuthToken(builder, authToken):
    VerbsAddAuthToken(builder, authToken)

def VerbsAddObject(builder, object):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(object), 0)

def AddObject(builder, object):
    VerbsAddObject(builder, object)

def VerbsAddInherited(builder, inherited):
    builder.PrependBoolSlot(3, inherited, 0)

def AddInherited(builder, inherited):
    VerbsAddInherited(builder, inherited)

def VerbsEnd(builder):
    return builder.EndObject()

def End(builder):
    return VerbsEnd(builder)
