# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VerbValue(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VerbValue()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVerbValue(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VerbValue
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VerbValue
    def VerbInfo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.VerbInfo import VerbInfo
            obj = VerbInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # VerbValue
    def Code(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.String(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return ""

    # VerbValue
    def CodeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # VerbValue
    def CodeIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def VerbValueStart(builder): builder.StartObject(2)
def Start(builder):
    return VerbValueStart(builder)
def VerbValueAddVerbInfo(builder, verbInfo): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(verbInfo), 0)
def AddVerbInfo(builder, verbInfo):
    return VerbValueAddVerbInfo(builder, verbInfo)
def VerbValueAddCode(builder, code): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(code), 0)
def AddCode(builder, code):
    return VerbValueAddCode(builder, code)
def VerbValueStartCodeVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartCodeVector(builder, numElems):
    return VerbValueStartCodeVector(builder, numElems)
def VerbValueEnd(builder): return builder.EndObject()
def End(builder):
    return VerbValueEnd(builder)