# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

class VerbProgramErrorUnion(object):
    NONE = 0
    NoVerbToProgram = 1
    VerbCompilationError = 2
    VerbDatabaseError = 3
