# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

class VerbProgramErrorUnion(object):
    NONE = 0
    NoVerbToProgram = 1
    VerbPermissionDenied = 2
    VerbCompilationError = 3
    VerbDatabaseError = 4
