# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class VerbProgramFailure(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = VerbProgramFailure()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsVerbProgramFailure(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # VerbProgramFailure
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # VerbProgramFailure
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.VerbProgramError import VerbProgramError
            obj = VerbProgramError()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def VerbProgramFailureStart(builder):
    builder.StartObject(1)

def Start(builder):
    VerbProgramFailureStart(builder)

def VerbProgramFailureAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def AddError(builder, error):
    VerbProgramFailureAddError(builder, error)

def VerbProgramFailureEnd(builder):
    return builder.EndObject()

def End(builder):
    return VerbProgramFailureEnd(builder)
