# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorkerAttached(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorkerAttached()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorkerAttached(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorkerAttached
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorkerAttached
    def Token(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.WorkerToken import WorkerToken
            obj = WorkerToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorkerAttached
    def WorkerId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Uuid import Uuid
            obj = Uuid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def WorkerAttachedStart(builder):
    builder.StartObject(2)

def Start(builder):
    WorkerAttachedStart(builder)

def WorkerAttachedAddToken(builder, token):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(token), 0)

def AddToken(builder, token):
    WorkerAttachedAddToken(builder, token)

def WorkerAttachedAddWorkerId(builder, workerId):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(workerId), 0)

def AddWorkerId(builder, workerId):
    WorkerAttachedAddWorkerId(builder, workerId)

def WorkerAttachedEnd(builder):
    return builder.EndObject()

def End(builder):
    return WorkerAttachedEnd(builder)
