# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorkerToken(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorkerToken()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorkerToken(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorkerToken
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorkerToken
    def Token(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def WorkerTokenStart(builder):
    builder.StartObject(1)

def Start(builder):
    WorkerTokenStart(builder)

def WorkerTokenAddToken(builder, token):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(token), 0)

def AddToken(builder, token):
    WorkerTokenAddToken(builder, token)

def WorkerTokenEnd(builder):
    return builder.EndObject()

def End(builder):
    return WorkerTokenEnd(builder)
