# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorkerToDaemonMessage(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorkerToDaemonMessage()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorkerToDaemonMessage(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorkerToDaemonMessage
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorkerToDaemonMessage
    def MessageType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # WorkerToDaemonMessage
    def Message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def WorkerToDaemonMessageStart(builder):
    builder.StartObject(2)

def Start(builder):
    WorkerToDaemonMessageStart(builder)

def WorkerToDaemonMessageAddMessageType(builder, messageType):
    builder.PrependUint8Slot(0, messageType, 0)

def AddMessageType(builder, messageType):
    WorkerToDaemonMessageAddMessageType(builder, messageType)

def WorkerToDaemonMessageAddMessage(builder, message):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(message), 0)

def AddMessage(builder, message):
    WorkerToDaemonMessageAddMessage(builder, message)

def WorkerToDaemonMessageEnd(builder):
    return builder.EndObject()

def End(builder):
    return WorkerToDaemonMessageEnd(builder)
