# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorkerInvalidPayload(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorkerInvalidPayload()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorkerInvalidPayload(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorkerInvalidPayload
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorkerInvalidPayload
    def Reason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def WorkerInvalidPayloadStart(builder):
    builder.StartObject(1)

def Start(builder):
    WorkerInvalidPayloadStart(builder)

def WorkerInvalidPayloadAddReason(builder, reason):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(reason), 0)

def AddReason(builder, reason):
    WorkerInvalidPayloadAddReason(builder, reason)

def WorkerInvalidPayloadEnd(builder):
    return builder.EndObject()

def End(builder):
    return WorkerInvalidPayloadEnd(builder)
