# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorkerPong(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorkerPong()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorkerPong(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorkerPong
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorkerPong
    def Token(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorRpc.WorkerToken import WorkerToken
            obj = WorkerToken()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # WorkerPong
    def WorkerType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Symbol import Symbol
            obj = Symbol()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def WorkerPongStart(builder):
    builder.StartObject(2)

def Start(builder):
    WorkerPongStart(builder)

def WorkerPongAddToken(builder, token):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(token), 0)

def AddToken(builder, token):
    WorkerPongAddToken(builder, token)

def WorkerPongAddWorkerType(builder, workerType):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(workerType), 0)

def AddWorkerType(builder, workerType):
    WorkerPongAddWorkerType(builder, workerType)

def WorkerPongEnd(builder):
    return builder.EndObject()

def End(builder):
    return WorkerPongEnd(builder)
