# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WorkerNotRegistered(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WorkerNotRegistered()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWorkerNotRegistered(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WorkerNotRegistered
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WorkerNotRegistered
    def WorkerId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Uuid import Uuid
            obj = Uuid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def WorkerNotRegisteredStart(builder):
    builder.StartObject(1)

def Start(builder):
    WorkerNotRegisteredStart(builder)

def WorkerNotRegisteredAddWorkerId(builder, workerId):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(workerId), 0)

def AddWorkerId(builder, workerId):
    WorkerNotRegisteredAddWorkerId(builder, workerId)

def WorkerNotRegisteredEnd(builder):
    return builder.EndObject()

def End(builder):
    return WorkerNotRegisteredEnd(builder)
