# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorRpc

class WorkerErrorUnion(object):
    NONE = 0
    WorkerPermissionDenied = 1
    WorkerInvalidRequest = 2
    WorkerInternalError = 3
    WorkerRequestTimedOut = 4
    WorkerRequestError = 5
    WorkerDetached = 6
    NoWorkerAvailable = 7
