#!/bin/sh

TELNET_CONF=/etc/moor/telnet-host-config.json

case "$1" in
purge)
    # Per https://www.debian.org/doc/debian-policy/ch-files.html#behavior
    # "configuration files must be preserved when the package is removed, and
    #  only deleted when the package is purged."
    # We leave the directory in place, but remove the contents for the telnet-host
    if [ -f ${TELNET_CONF} ]; then
        rm ${TELNET_CONF}
    fi
    ;;
esac

#DEBHELPER#

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	systemctl --system telnet-host-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask moor-telnet-host.service >/dev/null
	fi
fi
