# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorTask

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AbortTicks(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AbortTicks()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAbortTicks(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # AbortTicks
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AbortTicks
    def Ticks(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def AbortTicksStart(builder):
    builder.StartObject(1)

def Start(builder):
    AbortTicksStart(builder)

def AbortTicksAddTicks(builder, ticks):
    builder.PrependUint64Slot(0, ticks, 0)

def AddTicks(builder, ticks):
    AbortTicksAddTicks(builder, ticks)

def AbortTicksEnd(builder):
    return builder.EndObject()

def End(builder):
    return AbortTicksEnd(builder)
