# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorTask

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BfFrameWrapper(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BfFrameWrapper()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBfFrameWrapper(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # BfFrameWrapper
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BfFrameWrapper
    def Frame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorTask.BfFrame import BfFrame
            obj = BfFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def BfFrameWrapperStart(builder):
    builder.StartObject(1)

def Start(builder):
    BfFrameWrapperStart(builder)

def BfFrameWrapperAddFrame(builder, frame):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(frame), 0)

def AddFrame(builder, frame):
    BfFrameWrapperAddFrame(builder, frame)

def BfFrameWrapperEnd(builder):
    return builder.EndObject()

def End(builder):
    return BfFrameWrapperEnd(builder)
