# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorTask

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CatchType(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CatchType()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCatchType(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CatchType
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CatchType
    def CatchTypeType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # CatchType
    def CatchType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def CatchTypeStart(builder):
    builder.StartObject(2)

def Start(builder):
    CatchTypeStart(builder)

def CatchTypeAddCatchTypeType(builder, catchTypeType):
    builder.PrependUint8Slot(0, catchTypeType, 0)

def AddCatchTypeType(builder, catchTypeType):
    CatchTypeAddCatchTypeType(builder, catchTypeType)

def CatchTypeAddCatchType(builder, catchType):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(catchType), 0)

def AddCatchType(builder, catchType):
    CatchTypeAddCatchType(builder, catchType)

def CatchTypeEnd(builder):
    return builder.EndObject()

def End(builder):
    return CatchTypeEnd(builder)
