# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorTask

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class CatchErrors(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CatchErrors()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCatchErrors(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CatchErrors
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CatchErrors
    def Errors(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorCommon.Error import Error
            obj = Error()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # CatchErrors
    def ErrorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CatchErrors
    def ErrorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def CatchErrorsStart(builder):
    builder.StartObject(1)

def Start(builder):
    CatchErrorsStart(builder)

def CatchErrorsAddErrors(builder, errors):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(errors), 0)

def AddErrors(builder, errors):
    CatchErrorsAddErrors(builder, errors)

def CatchErrorsStartErrorsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartErrorsVector(builder, numElems: int) -> int:
    return CatchErrorsStartErrorsVector(builder, numElems)

def CatchErrorsEnd(builder):
    return builder.EndObject()

def End(builder):
    return CatchErrorsEnd(builder)
