# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorTask

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EnvironmentScope(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EnvironmentScope()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEnvironmentScope(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # EnvironmentScope
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EnvironmentScope
    def Vars(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from MoorVar.Var import Var
            obj = Var()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # EnvironmentScope
    def VarsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # EnvironmentScope
    def VarsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def EnvironmentScopeStart(builder):
    builder.StartObject(1)

def Start(builder):
    EnvironmentScopeStart(builder)

def EnvironmentScopeAddVars(builder, vars):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(vars), 0)

def AddVars(builder, vars):
    EnvironmentScopeAddVars(builder, vars)

def EnvironmentScopeStartVarsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartVarsVector(builder, numElems: int) -> int:
    return EnvironmentScopeStartVarsVector(builder, numElems)

def EnvironmentScopeEnd(builder):
    return builder.EndObject()

def End(builder):
    return EnvironmentScopeEnd(builder)
