# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorTask

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FinallyReason(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FinallyReason()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFinallyReason(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FinallyReason
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FinallyReason
    def ReasonType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # FinallyReason
    def Reason(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def FinallyReasonStart(builder):
    builder.StartObject(2)

def Start(builder):
    FinallyReasonStart(builder)

def FinallyReasonAddReasonType(builder, reasonType):
    builder.PrependUint8Slot(0, reasonType, 0)

def AddReasonType(builder, reasonType):
    FinallyReasonAddReasonType(builder, reasonType)

def FinallyReasonAddReason(builder, reason):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(reason), 0)

def AddReason(builder, reason):
    FinallyReasonAddReason(builder, reason)

def FinallyReasonEnd(builder):
    return builder.EndObject()

def End(builder):
    return FinallyReasonEnd(builder)
