# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorTask

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FinallyExit(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FinallyExit()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFinallyExit(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FinallyExit
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FinallyExit
    def Stack(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # FinallyExit
    def Label(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def FinallyExitStart(builder):
    builder.StartObject(2)

def Start(builder):
    FinallyExitStart(builder)

def FinallyExitAddStack(builder, stack):
    builder.PrependUint64Slot(0, stack, 0)

def AddStack(builder, stack):
    FinallyExitAddStack(builder, stack)

def FinallyExitAddLabel(builder, label):
    builder.PrependUint16Slot(1, label, 0)

def AddLabel(builder, label):
    FinallyExitAddLabel(builder, label)

def FinallyExitEnd(builder):
    return builder.EndObject()

def End(builder):
    return FinallyExitEnd(builder)
