# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorTask

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MooFrame(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MooFrame()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMooFrame(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MooFrame
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MooFrame
    def Frame(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorTask.MooStackFrame import MooStackFrame
            obj = MooStackFrame()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def MooFrameStart(builder):
    builder.StartObject(1)

def Start(builder):
    MooFrameStart(builder)

def MooFrameAddFrame(builder, frame):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(frame), 0)

def AddFrame(builder, frame):
    MooFrameAddFrame(builder, frame)

def MooFrameEnd(builder):
    return builder.EndObject()

def End(builder):
    return MooFrameEnd(builder)
