# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorTask

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class PcLambda(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = PcLambda()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsPcLambda(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # PcLambda
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # PcLambda
    def Offset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def PcLambdaStart(builder):
    builder.StartObject(1)

def Start(builder):
    PcLambdaStart(builder)

def PcLambdaAddOffset(builder, offset):
    builder.PrependUint64Slot(0, offset, 0)

def AddOffset(builder, offset):
    PcLambdaAddOffset(builder, offset)

def PcLambdaEnd(builder):
    return builder.EndObject()

def End(builder):
    return PcLambdaEnd(builder)
