# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorTask

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ScopeTryFinally(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScopeTryFinally()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScopeTryFinally(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ScopeTryFinally
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ScopeTryFinally
    def Label(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def ScopeTryFinallyStart(builder):
    builder.StartObject(1)

def Start(builder):
    ScopeTryFinallyStart(builder)

def ScopeTryFinallyAddLabel(builder, label):
    builder.PrependUint16Slot(0, label, 0)

def AddLabel(builder, label):
    ScopeTryFinallyAddLabel(builder, label)

def ScopeTryFinallyEnd(builder):
    return builder.EndObject()

def End(builder):
    return ScopeTryFinallyEnd(builder)
