# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorTask

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ScopeWhile(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ScopeWhile()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsScopeWhile(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ScopeWhile
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def ScopeWhileStart(builder):
    builder.StartObject(0)

def Start(builder):
    ScopeWhileStart(builder)

def ScopeWhileEnd(builder):
    return builder.EndObject()

def End(builder):
    return ScopeWhileEnd(builder)
