# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorTask

class ScopeTypeUnion(object):
    NONE = 0
    ScopeTryFinally = 1
    ScopeTryCatch = 2
    ScopeIf = 3
    ScopeEif = 4
    ScopeWhile = 5
    ScopeFor = 6
    ScopeForSequence = 7
    ScopeForRange = 8
    ScopeBlock = 9
    ScopeComprehension = 10
