# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorTask

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class StartEval(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = StartEval()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsStartEval(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # StartEval
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # StartEval
    def Player(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Obj import Obj
            obj = Obj()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # StartEval
    def Program(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorProgram.StoredProgram import StoredProgram
            obj = StoredProgram()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def StartEvalStart(builder):
    builder.StartObject(2)

def Start(builder):
    StartEvalStart(builder)

def StartEvalAddPlayer(builder, player):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(player), 0)

def AddPlayer(builder, player):
    StartEvalAddPlayer(builder, player)

def StartEvalAddProgram(builder, program):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(program), 0)

def AddProgram(builder, program):
    StartEvalAddProgram(builder, program)

def StartEvalEnd(builder):
    return builder.EndObject()

def End(builder):
    return StartEvalEnd(builder)
