# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorTask

class TaskStartUnion(object):
    NONE = 0
    StartCommandVerb = 1
    StartDoCommand = 2
    StartVerb = 3
    StartFork = 4
    StartEval = 5
