# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorTask

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WakeTime(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WakeTime()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWakeTime(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WakeTime
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WakeTime
    def Nanos(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def WakeTimeStart(builder):
    builder.StartObject(1)

def Start(builder):
    WakeTimeStart(builder)

def WakeTimeAddNanos(builder, nanos):
    builder.PrependUint64Slot(0, nanos, 0)

def AddNanos(builder, nanos):
    WakeTimeAddNanos(builder, nanos)

def WakeTimeEnd(builder):
    return builder.EndObject()

def End(builder):
    return WakeTimeEnd(builder)
