# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorTask

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WakeCondition(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WakeCondition()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWakeCondition(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WakeCondition
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WakeCondition
    def ConditionType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # WakeCondition
    def Condition(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def WakeConditionStart(builder):
    builder.StartObject(2)

def Start(builder):
    WakeConditionStart(builder)

def WakeConditionAddConditionType(builder, conditionType):
    builder.PrependUint8Slot(0, conditionType, 0)

def AddConditionType(builder, conditionType):
    WakeConditionAddConditionType(builder, conditionType)

def WakeConditionAddCondition(builder, condition):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(condition), 0)

def AddCondition(builder, condition):
    WakeConditionAddCondition(builder, condition)

def WakeConditionEnd(builder):
    return builder.EndObject()

def End(builder):
    return WakeConditionEnd(builder)
