# automatically generated by the FlatBuffers compiler, do not modify

# namespace: MoorTask

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class WakeInput(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = WakeInput()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsWakeInput(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # WakeInput
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # WakeInput
    def Uuid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from MoorCommon.Uuid import Uuid
            obj = Uuid()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def WakeInputStart(builder):
    builder.StartObject(1)

def Start(builder):
    WakeInputStart(builder)

def WakeInputAddUuid(builder, uuid):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(uuid), 0)

def AddUuid(builder, uuid):
    WakeInputAddUuid(builder, uuid)

def WakeInputEnd(builder):
    return builder.EndObject()

def End(builder):
    return WakeInputEnd(builder)
