[book]
authors = ["Zoltán Nagy", "Ryan Daum"]
language = "en"
multilingual = false
src = "src"
title = "The mooR Book"

[output.html]
additional-css = ["theme/style.css", "theme/pagetoc.css"]
additional-js = ["theme/moo-syntax-highlight.js", "theme/pagetoc.js"]

[output.linkcheck]

[preprocessor.pagetoc]
