{
 "title": "Server dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "WebSockets server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ws_server_new_connection", "legendFormat": "New connection" },
    { "expr": "ws_server_message_received", "legendFormat": "Message received" },
    { "expr": "ws_server_connection_finished", "legendFormat": "Disconnect" }
   ]
  },
  {
   "title": "Db Tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rocksdb_start_transaction_server",
     "legendFormat": "Start Tx Server"
    },
    { "expr": "rocksdb_tx_start", "legendFormat": "Rocks Tx Start" },
    { "expr": "rocksdb_tx_commit", "legendFormat": "Rocks Commit" }
   ]
  },
  {
   "title": "Scheduler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "scheduler_tasks", "legendFormat": "Scheduled tasks" },
    { "expr": "scheduler_created_tasks", "legendFormat": "Created tasks" },
    { "expr": "scheduler_boot_player", "legendFormat": "Terminated player" },
    { "expr": "scheduler_submit_command_task", "legendFormat": "Command tasks" },
    { "expr": "scheduler_task_succeeded", "legendFormat": "Succeeded" },
    {},
    { "expr": "task_start_command", "legendFormat": "Command task started" },
    { "expr": "tasks_success_complete", "legendFormat": "Tasks completed" },
    {}
   ]
  }
 ]
}